<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-07 17:13
=======
# Generated by Django 5.1.6 on 2025-02-07 11:13
>>>>>>> ddbec83850b43b89e65dc713f6ffc768ac78e5db

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
=======
            name='Person',
>>>>>>> ddbec83850b43b89e65dc713f6ffc768ac78e5db
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
