# Generated by Django 5.1.6 on 2025-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeId', models.IntegerField(max_length=100)),
                ('reviewerId', models.IntegerField(max_length=100)),
                ('rating', models.IntegerField(max_length=1)),
                ('reviewString', models.CharField(max_length=200)),
            ],
        ),
    ]
