# Generated by Django 5.1.6 on 2025-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipeId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewerId',
            field=models.IntegerField(),
        ),
    ]
