# Generated by Django 5.1.6 on 2025-02-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating_alter_review_recipeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='reviewRating',
        ),
    ]
