# Generated by Django 5.1.6 on 2025-02-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
