# Generated by Django 5.1.5 on 2025-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=100)),
                ('ingredientMeasurementUnit', models.CharField(max_length=100)),
                ('caloriesPerUnit', models.IntegerField()),
                ('proteinPerUnit', models.IntegerField()),
                ('fatPerUnit', models.IntegerField()),
                ('carbsPerUnit', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='recipeName',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cookDifficulty',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(default=str, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='is_ingredient_of', to='recipes.ingredients'),
        ),
    ]
