# Generated by Django 5.1.5 on 2025-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredients_rename_title_recipe_recipename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
