# Generated by Django 5.1.5 on 2025-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
    ]
