# Generated by Django 5.1.5 on 2025-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_ingredients_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='asda', max_length=1000),
            preserve_default=False,
        ),
    ]
