# Generated by Django 5.1.5 on 2025-02-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
