# Generated by Django 5.1.6 on 2025-03-13 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_ingredients_cookedby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookedby',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_ingredient_of', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='cookedby',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_ingredients', to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='UserIngredientsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='recipes.ingredients')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
