# Generated by Django 5.1.6 on 2025-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_cookedby_ingredient_alter_cookedby_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useringredientsinventory',
            old_name='ingredientId',
            new_name='ingredient',
        ),
        migrations.AlterField(
            model_name='useringredientsinventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
