# Generated by Django 5.1.6 on 2025-04-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_useringredientsinventory_ingredientid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
