# Generated by Django 5.1.6 on 2025-04-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipeingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookedBy',
        ),
    ]
